server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /order-ecommerce

spring:
  application:
    name: order-ecommerce
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orderecommerce_db?currentSchema=public
    username: postgres
    password: 123456no
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      autocommit: false
      poolname: order-ecommerce
      validationTimeout: 60000
logging:
  level:
    sql: trace
